hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - optim.online_ratio=1.0,0.5,0.0
    - logger.mode=offline
  job:
    name: discrete_sac
    chdir: null
    override_dirname: logger.mode=offline,optim.online_ratio=1.0,0.5,0.0
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/kfu38/rl/sota-implementations/discrete_sac
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/kfu38/rl/sota-implementations/discrete_sac
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
env:
  name: CartPole-v1
  task: ''
  library: gym
  seed: 42
  max_episode_steps: 500
collector:
  total_frames: 100000
  init_random_frames: 1000
  init_env_steps: 10000
  frames_per_batch: 500
  reset_at_each_iter: false
  device: cpu
  env_per_collector: 1
  num_workers: 1
  offline_frames: 10000
replay_buffer:
  prb: false
  size: 1000000
  scratch_dir: null
optim:
  utd_ratio: 1.0
  gamma: 0.99
  batch_size: 256
  online_ratio: 1.0
  lr: 0.0003
  weight_decay: 0.0
  target_update_polyak: 0.995
  target_entropy_weight: 0.2
  target_entropy: auto
  loss_function: l2
network:
  hidden_sizes:
  - 256
  - 256
  activation: relu
  device: cpu
logger:
  backend: wandb
  project_name: torchrl_example_discrete_sac
  group_name: ablate-symmetric-sampling
  exp_name: ${env.name}_DiscreteSAC
  mode: offline
  eval_iter: 5000
  video: true
